version: '3'

services:
  db_great_danes:
    image: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - great_danes_new_data:/var/lib/postgresql/data

volumes:
  great_danes_new_data:
